### ISSUE TITLE
Patch Module::Build on CPAN to support PERL_USE_UNSAFE_INC

### ISSUE THREAD

**Issue by toddr** [toddr/perl#4]
Current cPanel patch is: https://gist.github.com/toddr/d77d8d5fa9caa8f96b7758a126caa4dc

**Comment by Leont** [comment]
Do note that MB remembers the @INC of configure time for later phases, so if it's set correctly during `perl Build.PL` no later modification should be necessary for itself (for Module::Build::Tiny this isn't relevant anyway).

**Comment by toddr** [comment]
This ticket is about Module::Build not M:B:Tiny so I'm not sure what you're saying exactly.

WRT MB remembering @INC, that doesn't help since the environment variable PERL_USE_UNSAFE_INC=1 would have to be set PRIOR to perl Build.PL executing. If you could point me to where it does the "remembering" that might be the best place for us to inject into @INC but remember: you still have ANY process that might be called by `Build` which also needs @INC to include . so it's not just about M:B having . in @INC, it's unit tests and other builder code that might need it too.

**Comment by Leont** [comment]
> WRT MB remembering @INC, that doesn't help since the environment variable PERL_USE_UNSAFE_INC=1 would have to be set PRIOR to perl Build.PL executing.

Generally speaking (but not always), builder code an MB extension loads is also loaded during configuration (unless lazy loading is used), so I would expect unsafe-inc to be needed at that early stage already.

**Comment by toddr** [comment]
> This obviously doesn't cover tests, hence my "for itself".

Sure but presumably we'd want to fix M::B* so their own tests don't depend on . in @INC. I'm not sure where this leaves things. What alternative patch do you propose?

**Comment by Leont** [comment]
> What alternative patch do you propose?

All install tools run their tests using Test::Harness/TAP::Harness, so I think it makes sense to adapt that (though one can argue over the details of doing that, I'd go for adding an option to TAP::Harness and enabling it by default in Test::Harness).

**Comment by toddr** [comment]
The discussion of this patch has moved to the Module::Build repo via https://github.com/Perl-Toolchain-Gang/Module-Build/issues/69
