### ISSUE TITLE
Get support for PERL_USE_UNSAFE_INC into Module::Build::Tiny on CPAN.

### ISSUE THREAD

**Issue by toddr** [toddr/perl#6]
cPanel fixed it like this: https://gist.github.com/toddr/cba948fba1b791b3301244e626391866

**Comment by Leont** [comment]
What does this solve? Is it any issue observed in practice, only only suspected to exist?

**Comment by toddr** [comment]
Modules that use Module::Build::Tiny for their installation were failing to install without this patch. I would have to do some archeology to tell you which ones.

**Comment by toddr** [comment]
It was one of these:

aliased/aliased/Build.PL
Catalyst-Controller-ActionRole/Catalyst-Controller-ActionRole/Build.PL
Class-C3-Adopt-NEXT/Class-C3-Adopt-NEXT/Build.PL
Dist-Zilla-Plugin-GitHub/Dist-Zilla-Plugin-GitHub/Build.PL
Hook-LexWrap/Hook-LexWrap/Build.PL
IO-Socket-Timeout/IO-Socket-Timeout/Build.PL
LWP-Protocol-PSGI/LWP-Protocol-PSGI/Build.PL
Module-Build-Tiny/Module-Build-Tiny/Build.PL
Module-Runtime-Conflicts/Module-Runtime-Conflicts/Build.PL
MooseX-ConfigFromFile/MooseX-ConfigFromFile/Build.PL
MooseX-Daemonize/MooseX-Daemonize/Build.PL
MooseX-Getopt/MooseX-Getopt/Build.PL
MooseX-LazyRequire/MooseX-LazyRequire/Build.PL
MooseX-Object-Pluggable/MooseX-Object-Pluggable/Build.PL
MooseX-Role-Parameterized/MooseX-Role-Parameterized/Build.PL
MooseX-SimpleConfig/MooseX-SimpleConfig/Build.PL
MooseX-Types-Common/MooseX-Types-Common/Build.PL
MooseX-Types-DateTime/MooseX-Types-DateTime/Build.PL
MooseX-Types-LoadableClass/MooseX-Types-LoadableClass/Build.PL
MooseX-Types/MooseX-Types/Build.PL
MooseX-Types-Path-Class/MooseX-Types-Path-Class/Build.PL
MooseX-Types-Path-Tiny/MooseX-Types-Path-Tiny/Build.PL
PerlIO-via-Timeout/PerlIO-via-Timeout/Build.PL
Plack-Middleware-Session/Plack-Middleware-Session/Build.PL
Redis/Redis/Build.PL
SQL-Maker/SQL-Maker/Build.PL
Starman/Starman/Build.PL

**Comment by karenetheridge** [comment]
It would be helpful to see how any of these modules failed `./Build test`.  I think we may want to solve this a different way in the toolchain.

**Comment by toddr** [comment]
Could you be more specific? What different way do you want to solve it? Where is the conversation being had?

**Comment by karenetheridge** [comment]
> What different way do you want to solve it?

Since I don't know yet what "It" is, I can't really give you an answer yet.

**Comment by Leont** [comment]
I would be surprised if it was common or complicated, unlike other install tools it can't be a build issue, and there's already a norm of `use lib 't/lib'`. It may actually be a simpler fix on the long run to fix that (probably one) dist and be done with it.

**Comment by toddr** [comment]
Discussion moved to https://github.com/Perl-Toolchain-Gang/Module-Build/issues/69

**Comment by toddr** [comment]
Pull request opened for further discussion here:
